[project]
name = "pdf-a-converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "customtkinter>=5.2.2",
    "rich==14.0.0",
    "tkinterdnd2>=0.4.3",
]
